### ISSUE TITLE
Error in app/__init__.py

### ISSUE THREAD

**Issue by yevagorbachev** [Mandy-Zheng/Eclipse#10]
Error when running `app/__init__.py`
```
Traceback (most recent call last):
  File "__init__.py", line 149, in <module>
    loadData(countries, 'static/data/covid_countries.csv')
  File "__init__.py", line 24, in loadData
    row[0] = date.fromisoformat('-'.join((datestring[:4], datestring[4:6], datestring[6:])))
AttributeError: type object 'datetime.date' has no attribute 'fromisoformat'
```
Environment: Python 3.6.9
Commands executed:
```
 1999  git clone https://github.com/Mandy-Zheng/Eclipse.git
 2000  python3 -m venv covid19_venv
 2001  . covid19_venv/bin/activate
 2002  cd Eclipse/
 2003  pip3 install -r requirements.txt
 2004  cd app/
 2005  python3 app.py
 2006  dir
 2007  python3 __init__.py
```

**Comment by Mandy-Zheng** [comment]
fixed thanks!
